export const dishes = [
  {
    id: 1,
    title: "Makhni karahi",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 2,
    title: "Achaar Gosht",
    image: "",
    category: "Dinner",
    label: "Hot",
    price: "1678",
    desc: "A Hot and sicy Achaar Gosht handi with raita and salad",
  },
  {
    id: 3,
    title: "Butt karahi",
    image: "",
    category: "Dinner",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 4,
    title: "Dum Kabab",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 5,
    title: "Hot Pizza",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 6,
    title: "Channa-Gosht with Naan ",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 7,
    title: "Chicken Biryani",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
  {
    id: 8,
    title: "Chicken Jal-Farezi",
    image: "",
    category: "Lunch",
    label: "Hot",
    price: "1998",
    desc: "A Hot and sicy makhni karahi with raita and salad",
  },
];
